### ISSUE TITLE
Timestamps should default now()

### ISSUE THREAD

**Issue by paganotoni** [gobuffalo/pop#486] opened 2019-11-29 17:03 UTC
This would make a lot of things easier, things like fixtures and SQL inserts would become simpler with this change.

**Comment by cmhakkim** [comment] 2019-12-30 13:39
Duplicate of https://github.com/gobuffalo/pop/issues/455 but the issue is still valid.

**Comment by cmhakkim** [comment] 2019-12-30 13:45
Oh. I'm circumventing this by using database defaults triggers to set timestamps and I've marked these columns as read-only with `rw:"r"` tag.

**Closed** 2022-11-05 18:57 UTC
