### ISSUE TITLE
Add support MSSQL in future..?

### ISSUE THREAD

**Issue by EOM** [gobuffalo/pop#259] opened 2018-10-01 20:26 UTC
Hello! Thank you so much for your interest in Pop. 
Add support MSSQL in future for Buffalo..?
Add suport ORM to http://gorm.io or http://xorm.io

**Comment by mclark4386** [comment] 2018-10-01 20:28
Someone is working on a separate plugin for buffalo for gorm, but pop will be separate. A MSSQL dialect is more than welcome! If you have any questions about how to add a dialect please feel free to ask here or in the slack!

**Comment by EOM** [comment] 2018-10-01 20:53
What a pity because I find Buffalo interesting. Since it looks a lot like Rails or CakePHP but in these I have MSSQL support.
The only thing I found that is not something native to Buffalo, is to integrate GORM as a figure in this project.
https://github.com/markbates/gormrecipe

And GORM supports MSSQL, I'm new to GO and I'm looking at frameworks to enter to use GO with code generator like Buffalo, Beego, ABCWEB, etc.

**Comment by mclark4386** [comment] 2018-10-01 21:45
https://github.com/crolly/buffalo-gorm is the plugin, but I have no clue how far along they are... It's actually not terrible to add a dialect, but I understand it can seem daunting, especially when you are still learning the language. Stay toned and join the slack if you haven't, things move very quickly here^^

**Comment by marpio** [comment] 2018-10-02 06:29
The support for MS SQL Server is blocked until https://github.com/jmoiron/sqlx/pull/406 gets merged.

**Comment by stanislas-m** [comment] 2018-11-10 20:31
MS SQL Server support just got merged in fizz. :)

**Comment by stanislas-m** [comment] 2018-11-10 20:37
Duplicate of #40.

**Closed by stanislas-m** 2018-11-10 20:37 UTC
