### ISSUE TITLE
Duplicate records on creation 

### ISSUE THREAD

**Issue by alphonse927** [gobuffalo/pop#308] opened 2018-11-15 20:30 UTC
I recently upgrade Pop to the version 4.9.0 and found that when I create a record on the DB with a model that have associations with the struct tags "many_to_many" (Without Eager Create), it duplicates the entries, one with the association ID and another with the ID null "00000000-0000-0000-0000-000000000000".

```go
type Shop struct {
	ID            uuid.UUID  `json:"id" db:"id"`
	CreatedAt     time.Time  `json:"created_at" db:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at" db:"updated_at"`
	Name          string     `json:"name" db:"name"`

	Clients   Clients   `many_to_many:"shop_clients"`
	Employees Employees `many_to_many:"shop_employees"`
}
```

Association 1 Table
```
                  id                  |              shop_id                 |             employee_id              |         created_at         |         updated_at
--------------------------------------+--------------------------------------+--------------------------------------+----------------------------+----------------------------
 a2586835-5c58-4df0-8a51-897fbdef3fa9 | cf0b46ac-4523-422d-8bee-6f55e09f3ab5 | 99db3bcf-dae9-4479-8b7e-5cd7a02a7123 | 2018-11-15 15:02:51.050725 | 2018-11-15 15:02:51.050726 
 19177d09-a662-4172-8239-b69cc64cb14b | cf0b46ac-4523-422d-8bee-6f55e09f3ab5 | 00000000-0000-0000-0000-000000000000 | 2018-11-15 15:02:51.050725 | 2018-11-15 15:02:51.050726
```

Association 2 Table 
```
                  id                  |              shop_id                 |              client_id               |         created_at         |         updated_at
--------------------------------------+--------------------------------------+--------------------------------------+----------------------------+----------------------------
 cc70ce92-bd7e-408a-b559-bce52959b7ab | cf0b46ac-4523-422d-8bee-6f55e09f3ab5 | 00000000-0000-0000-0000-000000000000 | 2018-11-15 14:44:39.724305 | 2018-11-15 14:44:39.724305
 b032ad4f-9488-4c0a-a1b1-d7ea32eb2d97 | cf0b46ac-4523-422d-8bee-6f55e09f3ab5 | 99db3bcf-dae9-4479-8b7e-5cd7a02a7123 | 2018-11-15 14:44:39.742794 | 2018-11-15 14:44:39.742796
```

**Comment by mclark4386** [comment] 2018-11-16 20:52
Thank you for the report! I can confirm this is an issue and will try to get it fixed ASAP!

**Comment by alphonse927** [comment] 2018-11-16 21:04
I noticed that leaving the "executors.go" file as is was on v4.8.8 will work as before, BUT, I don't know how this could affect other associations.

```go
func (c *Connection) Create(model interface{}, excludeColumns ...string) error {
	if c.eager {
		return c.eagerCreate(model, excludeColumns...)
	}

	sm := &Model{Value: model}
	return sm.iterate(func(m *Model) error {
		return c.timeFunc("Create", func() error {
			var err error
			if err = m.beforeSave(c); err != nil {
				return err
			}

			if err = m.beforeCreate(c); err != nil {
				return err
			}

			tn := m.TableName()
			cols := columns.ForStructWithAlias(m.Value, tn, m.As)

			if tn == sm.TableName() {
				cols.Remove(excludeColumns...)
			}

			m.touchCreatedAt()
			m.touchUpdatedAt()

			if err = c.Dialect.Create(c.Store, m, cols); err != nil {
				return err
			}

			if err = m.afterCreate(c); err != nil {
				return err
			}

			return m.afterSave(c)
		})
	})
}
```

**Comment by mclark4386** [comment] 2018-11-16 21:07
Right, because that takes all the Flat associations work out. I'll be pushing a fix so that it only makes associations with the existing items in flat mode ASAP. I'll be tagging this issue in the PR as soon as it's ready and then when merged it'll be in the development branch until a release, so please look forward to it!^^;

**Comment by alphonse927** [comment] 2018-11-16 21:10
Thanks @mclark4386

**Comment by mclark4386** [comment] 2018-11-16 23:19
@alphonse927 Thanks for finding that! Should be fixed in #312 hopefully merged and released soon^^

**Closed** 2018-11-17 08:06 UTC
