### ISSUE TITLE
update many to many relation

### ISSUE THREAD

**Issue by gmolveau** [gobuffalo/pop#143] opened 2018-06-26 09:04 UTC
Hi, I could'nt find it in the documentation so, are there any methods to update a many-to-many relation ?

If, for example, I have `Driver [n] <-> [n] Car`, is there a `Driver.addCar` and `Driver.removeCar` methods ?

Thank's for your help !

**Comment by sio4** [comment] 2022-09-20 11:28
Since `Driver` and `Car` is your model, It depends on what exactly you want to do. Since the issue is too old, I am closing it for now, but if you still facing an issue with it, please feel free to reopen it with the details about your situation and examples.

**Closed by sio4** 2022-09-20 11:28 UTC
Labels: associations
