### ISSUE TITLE
MySQL `Delete` doesn't work when combined with `Where ... in (?)`

### ISSUE THREAD

**Issue by grantzvolsky** [gobuffalo/pop#699] opened 2022-04-04 15:30 UTC
## Description

Suppose the query

```
err = tx.RawQuery("DELETE FROM songs WHERE id in (?)", []uuid.UUID{u1.ID, u3.ID}).Exec()
```

This works fine, but we'd like to use Pop instead of RawQuery. So we write

```
ids := []uuid.UUID{u1.ID, u3.ID}
err = tx.Where("id in (?)", ids).Delete(&Song{})
```

This works with all dialects except for MySQL. With MySQL, we get

```
mysql delete: sql: converting argument $2 type: unsupported type []string, a slice of string
```

### Steps to Reproduce the Problem

```
pushd $(mktemp -d)
git clone --depth 10 git@github.com:grantzvolsky/pop.git -b issue/mysql-query-slice-delete
cd pop
make release-test
```

### Expected Behavior

Provided testcase doesn't fail.

### Actual Behavior

Provided testcase fails whith MySQL; works with other dialects.

### Workarounds

```
ids := []uuid.UUID{u1.ID, u3.ID}
iids := make([]interface{}, len(ids))
for i, v := range ids {
	iids[i] = v
}
err = tx.Where("id in (?)", iids...).Delete(&Song{})
```

### Info

OS: Linux 5.13.0-37-generic
Pop: 32f6994 [development] feat: support embedded struct fields (#691)

**Comment by sio4** [comment] 2022-09-24 13:20
Found the cause of the issue, fixed with PR #784, and will be released as v6.0.7 soon.

**Closed** 2022-09-24 13:23 UTC
Labels: bug, f: sql
