### ISSUE TITLE
ValidateAndUpdate without eager

### ISSUE THREAD

**Issue by elicas** [gobuffalo/pop#359] opened 2019-03-05 11:04 UTC
In the ValidateAndCreate() function, relations in DB are processed (with eager).
It's not the case for ValidateAndUpdate().
Could you please fix this issue?

**Comment by stanislas-m** [comment] 2019-03-05 12:38
Duplicate of #136

**Closed by stanislas-m** 2019-03-05 12:38 UTC

**Comment by elicas** [comment] 2019-03-05 13:51
Sorry for the duplication... I was looking in the wrong place...
Do you have an idea about the date... when will the "update" be operational?
