### ISSUE TITLE
Tables with sql syntax as column names, can't insert data

### ISSUE THREAD

**Issue by BartWillems** [gobuffalo/pop#48] opened 2018-03-28 17:52 UTC
```sql
INSERT INTO table_name (created_at, from, id, order, table, updated_at) VALUES (:created_at, :from, :id, :order, :table, :updated_at)
pq: syntax error at or near "from"
```

I also get this error the columns. The  only way to get around is, is to quote the query:
```sql
INSERT INTO table_name (created_at, "from", id, "order", "table", updated_at) VALUES (:created_at, :from, :id, :order, :table, :updated_at)
```

**Comment by stanislas-m** [comment] 2018-04-16 12:16
I'm closing this issue, since it's a duplicate of #42.

**Closed by stanislas-m** 2018-04-16 12:16 UTC
Labels: duplicate
